(* ::Package:: *)

(* ::Input:: *)
(*(* Finds the plane such that projection onto this plane would match p2 onto p1*)*)
(*FindPlane[p1_,p2_]:=Module[{directionVector,mpoint,planeEquation,plotRange=3},*)
(**)
(*directionVector=(p2-p1)/Norm[p2-p1];*)
(*mpoint=(Sqrt[3]+1)directionVector;*)
(**)
(*planeEquation=directionVector . ({x,y,z}-mpoint)==0;*)
(*planeEquation*)
(*]*)


(* ::Input:: *)
(*(*Finds the projection of the coordinates onto the given plane*)*)
(*CurveProjectionCoord[coord_, plane_]:=Module[{coordprojected,len,t, c},*)
(* *)
(*len=Length[coord];*)
(*t=1;*)
(*coordprojected=Reap[While[t<=len,c=RegionNearest[ImplicitRegion[plane,{x,y,z}]]@coord[[t]];Sow[c];t++]][[2,1]]*)
(*]*)
(**)
(*(*Plotting the projected co-ordinates*)*)
(*CurveProjectionCoordplot[coord_, plane_, color_]:=Module[{coordprojected, pt1, pt2, len,t, c},*)
(* *)
(*len=Length[coord];*)
(*t=1;*)
(*coordprojected=Reap[While[t<=len,c=RegionNearest[ImplicitRegion[plane,{x,y,z}]]@coord[[t]];Sow[c];t++]][[2,1]];*)
(**)
(*Show[ListLinePlot3D[coordprojected,PlotStyle->color], PlotRange-> All]*)
(*]*)
(**)
(*(*To calculate the scalar with which to normalise the distances between any two conecutive co-ordinates*)*)
(*Scalingfactor[coords1curve_, coords2curve_]:=Max[Abs[Union[coords1curve, coords2curve]]]*)
(**)
(*(*To find if point2 is between point1 and point3 in 3D*)*)


(* ::Input:: *)
(*containment[point1_, point2_, point3_]:=Module[{m, check},*)
(*check={};*)
(*Do[m=Which[point1[[i]]<= point2[[i]] <= point3[[i]] ,1,point1[[i]]>= point2[[i]]>=point3[[i]],1 , 0==0, 0];*)
(*AppendTo[check, m], {i, 1,3}*)
(*];*)
(**)
(*If[Total[check]==3, 1,0]*)
(*]*)
(**)
(*(*checks for intersection between any two given lines in 3D*)*)
(*lineintersection[a_,b_,c_,d_]:=Module[{inter, crosspar}, *)
(*(*{a, b} are points on line 1; {c, d} are points on line 2*)*)
(*crosspar=LeastSquares[Transpose[{b-a,c-d}], (c-a)];*)
(*If[Length[crosspar]>0, crosspar, Print["No Intersection"]]*)
(*]*)
(**)
(*(*To find all the coordinates between which we have the crossings*)*)
(*FindCrossingscoord[coords1proj_,coords2proj_]:=Module[{crossings1,crossings, line,linescurve1, linescurve2, linecurve1, linecurve2, cring,intersection, interpar, inter, pl},*)
(**)
(*line[coords_,i_,t_]:=coords[[i]] + t( coords[[i+1]]-coords[[i]]);*)
(**)
(*linescurve1=Table[line[coords1proj,i, t],{i,1,Length[coords1proj]-1,1}];*)
(*linescurve2=Table[line[coords2proj,i, s],{i,1,Length[coords2proj]-1,1}];*)
(**)
(**)
(*crossings1=Reap[Do[Do[*)
(*interpar= lineintersection[coords1proj[[i]],coords1proj[[i+1]], coords2proj[[j]], coords2proj[[j+1]]];*)
(*inter=line[coords1proj,i,interpar[[1]]];*)
(*intersection=If[containment[coords1proj[[i]], inter, coords1proj[[i+1]]]==1 && containment[coords2proj[[j]], inter, coords2proj[[j+1]]]==1 , 1, 0];*)
(**)
(*If[intersection==1 , Sow[{coords1proj[[i]],coords2proj[[j]], coords1proj[[i+1]], coords2proj[[j+1]], i, j, inter}]],{j,1,Length[coords2proj]-1}],{i,1,Length[coords1proj]-1}]];*)
(*If[Length[crossings1[[2]]]>0, crossings=crossings1[[2,1]], crossings={}];*)
(*crossings*)
(*]*)
(**)
(*(*Find intersections on the original curves with the line passing from the intersection point in the direction of the normal vector. These would then be the points on the original curve which map to the same point when projected along the normal vector.*)*)
(*crossingoriginalcurve[ coords1curve_,coords2curve_, crossings_, directionvector_]:=Module[{intpts, line1, line2,crpoints},*)
(*intpts={};*)
(*line1[i_, t_]:=crossings[[i,7]] + t( directionvector);*)
(*line2[coords_,i_,t_]:=coords[[i]] + t( coords[[i+1]]-coords[[i]]);*)
(**)
(*Do[*)
(*AppendTo[intpts,{lineintersection[crossings[[i,7]],line1[i,1],line2[coords1curve,crossings[[i,5]],0], line2[coords1curve,crossings[[i,5]],1]], lineintersection[crossings[[i,7]],line1[i,1],line2[coords2curve,crossings[[i,6]],0], line2[coords2curve,crossings[[i,6]],1]]}], {i,1, Length[crossings]}];*)
(*intpts;*)
(*crpoints={};*)
(*Do[AppendTo[crpoints, {line1[i,intpts[[i,1,1]]],line1[i,intpts[[i,2,1]]]}],{i,1, Length[intpts]}];*)
(*crpoints*)
(*]*)


(* ::Input:: *)
(*(*To find endmatched linking triples*)*)


(* ::Input:: *)
(*Computelinkingtriplesendmatched[listofchains_]:=Module[{coords1og, coords2og,sf,coords1, coords2,crossingvectors,tuplepos,cr1crossings, cr2crossings, cr1crossinginfo, cr2crossinginfo, cr1, cr2, tup, endcrvec1,endcrvec2,endmatched,vecang, coords1proj1, coords2proj1, coords1proj, coords2proj, crossings, directionvector, end1, end2, projplane,n, nnorm, endpoints, triples, triplesarray,  crlist, nulllist, triplestable, crpoints},*)
(**)
(*triplesarray={};(*Triples array stores all the linking triples*)*)
(**)
(*Do[ Do[If[j>i,*)
(*(*Iterative assignment of curves from the list of chains*)*)
(*coords1og=listofchains[[i]];*)
(*coords2og=listofchains[[j]];(*Scaling down the co-ordinates*)*)
(*sf=Scalingfactor[coords1og, coords2og];*)
(*coords1=coords1og/sf;*)
(*coords2=coords2og/sf;*)
(*(*Storing all the endpoints, this is used to find planes of projections and also to remove endmatched points from the list of crossings*)*)
(*endpoints={{coords1[[1]],coords2[[1]],1,1},{coords1[[1]],coords2[[Length[coords2]]],1,Length[coords2]-1}, {coords1[[Length[coords1]]],coords2[[1]], Length[coords1]-1, 1},{coords1[[Length[coords1]]],coords2[[Length[coords2]]], Length[coords1]-1, Length[coords2]-1}};*)
(*triples={};*)
(**)
(*Do[*)
(*(*Iteratively assigning the endpoints*)*)
(*end1=endpoints[[k,1]];*)
(*end2=endpoints[[k,2]];*)
(*projplane=FindPlane[end1, end2];*)
(*n=end2-end1;*)
(*nnorm=Norm[n];*)
(*directionvector=n/nnorm;*)
(**)
(*(*Taking projections*)*)
(*coords1proj=CurveProjectionCoord[coords1,projplane];*)
(*coords2proj=CurveProjectionCoord[coords2, projplane];*)
(*(*Finding crossings*)*)
(*crlist=FindCrossingscoord[coords1proj,coords2proj];*)
(**)
(*(*Removing endmatched co-ordinates from the list of crossings*)*)
(*If[Length[crlist]>0,*)
(*nulllist={};*)
(*Do[If[crlist[[l,5]]== endpoints[[k,3]]&&crlist[[l,6]]==endpoints[[k,4]], AppendTo[nulllist, crlist[[l]]]], {l, 1, Length[crlist]}];*)
(*crossings=DeleteElements[crlist, nulllist], crossings={}];*)
(**)
(*If[Length[crossings]>0,*)
(**)
(*(*Finding points on the original curve for each crossing in the projection*)*)
(*crpoints=crossingoriginalcurve[coords1, coords2, crossings, directionvector];*)
(**)
(*(*Defining crossing vectors and determining the angle between the vectors at each crossing*)*)
(*crossingvectors= Reap[Do[Sow[{crossings[[i,3]]-crossings[[i,1]],crossings[[i,4]]-crossings[[i,2]], VectorAngle[crossings[[i,3]]-crossings[[i,1]],crossings[[i,4]]-crossings[[i,2]]]}],{i,1,Length[crossings]}]][[2,1]];*)
(**)
(*(*Determining the position of each triple of crossings vectors and vector angle in the Linking triple based on A2 being the over curve or A1 being the over curve if the linking triple is L(A1,A2)*)*)
(*tuplepos=Reap[Do[If[Dot[crpoints[[i,2]]-crpoints[[i,1]],directionvector]>0, Sow[crossingvectors[[i]],{x}],Sow[crossingvectors[[i]],{y}]],{i, 1, Length[crossings]} ],{x,y}];*)
(**)
(*(*Checking if there are any crossings in each tuple position*)*)
(*If[Length[tuplepos[[2,1]]]> 0, cr1crossings=tuplepos[[2,1,1]], cr1crossings={}];*)
(*If[Length[tuplepos[[2,2]]]>0, cr2crossings=tuplepos[[2,2,1]], cr2crossings={}];*)
(**)
(*(*To find the crossing sign for each crossing*)*)
(*If[Length[cr1crossings]>0,*)
(*cr1crossinginfo= Reap[Do[If[Dot[RotationTransform[cr1crossings[[i,3]],directionvector][cr1crossings[[i,1]]], cr1crossings[[i,2]]]-Dot[RotationTransform[-cr1crossings[[i,3]],directionvector][cr1crossings[[i,1]]], cr1crossings[[i,2]]]> 0, Sow[-1], Sow[1]],{i, 1, Length[cr1crossings]}]][[2,1]],cr1crossinginfo={0}];*)
(*If[Length[cr2crossings]>0,*)
(*cr2crossinginfo= Reap[Do[If[Dot[RotationTransform[cr2crossings[[i,3]],directionvector][cr2crossings[[i,2]]], cr2crossings[[i,1]]]-Dot[RotationTransform[-cr2crossings[[i,3]],directionvector][cr2crossings[[i,2]]], cr2crossings[[i,1]]]>0, Sow[-1], Sow[1]],{i, 1, Length[cr2crossings]}]][[2,1]], cr2crossinginfo={0}];*)
(*, cr1crossinginfo=cr2crossinginfo={0}];*)
(*(*To find vectors at the endmatched point*)*)
(*endcrvec1=If[end1==coords1[[1]], coords1proj[[2]]-coords1proj[[1]], coords1proj[[Length[coords1proj]]]- coords1proj[[Length[coords1proj]-1]]];*)
(*endcrvec2=If[end2==coords2[[1]], coords2proj[[2]]-coords2proj[[1]], coords2proj[[Length[coords2proj]]]- coords2proj[[Length[coords2proj]-1]]];*)
(*vecang=VectorAngle[endcrvec1,endcrvec2];*)
(**)
(*cr1= Total[cr1crossinginfo];*)
(*cr2= Total[cr2crossinginfo];*)
(**)
(*(*Finding endmatched crossing sign*)*)
(*endmatched=If[Dot[RotationTransform[vecang,directionvector][endcrvec1], endcrvec2]-Dot[RotationTransform[-vecang,directionvector][endcrvec1], endcrvec2]>0, -1,1];*)
(*AppendTo[triples,{cr1,cr2,endmatched}], {k, 1, Length[endpoints]}];*)
(*AppendTo[triplesarray,{{i, j},triples}]]*)
(*, {j, 1, Length[listofchains]}], {i, 1, Length[listofchains]}];*)
(*triplesarray*)
(*]*)
(**)
(*(*Presentation of the endmatched linking triples*)*)
(*endmatchedtriplestable[triplesarray_]:= Module[{triplestable},*)
(**)
(*triplestable= {{"Curve Pairs", "Lii", "Lit", "Lti","Ltt" }};*)
(**)
(*Do[ AppendTo[triplestable, {StringRiffle[{triplesarray[[i,1,1]],triplesarray[[i,1,2]]},{"(",",",")"}], StringRiffle[{triplesarray[[i,2,1,1]],triplesarray[[i,2,1,2]],triplesarray[[i,2,1,3]]},{"(",",",")"}], StringRiffle[{triplesarray[[i,2,2,1]],triplesarray[[i,2,2,2]],triplesarray[[i,2,2,3]]},{"(",",",")"}],StringRiffle[{triplesarray[[i,2,3,1]],triplesarray[[i,2,3,2]],triplesarray[[i,2,3,3]]},{"(",",",")"}],StringRiffle[{triplesarray[[i,2,4,1]],triplesarray[[i,2,4,2]],triplesarray[[i,2,4,3]]},{"(",",",")"}]}]*)
(*, {i, 1,Length[triplesarray]}];*)
(*triplestable//TableForm*)
(*]*)
(**)
(*(*Computing for all three junctions of a tensegrity triangle*)*)
(*junctioncomputations[J1_,J2_,J3_]:=Module[{tupposseqJ1,tupposseqJ1table,triplesarrayJ1,triplesseqallJ1, triplesseqJ1,tupposseqJ2,tupposseqJ2table,triplesarrayJ2,triplesseqallJ2,triplesseqJ2,tupposseqJ3,tupposseqJ3table,triplesarrayJ3,triplesseqallJ3,triplesseqJ3},*)
(**)
(*triplesarrayJ1=Computelinkingtriplesendmatched[J1];*)
(*triplesarrayJ2=Computelinkingtriplesendmatched[J2];*)
(*triplesarrayJ3=Computelinkingtriplesendmatched[J3];*)
(**)
(*{triplesarrayJ1,triplesarrayJ2,triplesarrayJ3,endmatchedtriplestable[triplesarrayJ1],endmatchedtriplestable[triplesarrayJ2],endmatchedtriplestable[triplesarrayJ3]}*)
(*]*)
(**)
(*(*To find endslide linking triples*)*)
(*Computelinkingtriplesendslide[listofchains_]:=Module[{coords1, coords2,crossingvectors,tuplepos,cr1crossings, cr2crossings, cr1crossinginfo, cr2crossinginfo, cr1, cr2, tup, endcrvec1,endcrvec2,endmatched,vecang, coords1proj1, coords2proj1, coords1proj, coords2proj, crossings, directionvector, end1, end2, projplane,n, nnorm, endpoints, triplesarray, triplesseq, crlist, nulllist, triplestable,chainlabels,list,chains,crpoints, triplesall,output},*)
(**)
(*triplesall={};(*Stores all triples together to find triples tally*)*)
(*triplesarray={};*)
(*Do[Do[If[i!=j,*)
(**)
(*coords1=listofchains[[i]];*)
(*coords2=listofchains[[j]];*)
(*endpoints=Union[ {{coords1[[1]], coords2[[1]], 1, 1}}, Table[{coords1[[1]], coords2[[i]], 1, i -1},{i,2,Length[coords2]}]];*)
(*triplesseq={};*)
(**)
(*Do[*)
(*end1=endpoints[[k,1]];*)
(*end2=endpoints[[k,2]];*)
(*projplane=FindPlane[end1, end2];*)
(*n=end2-end1;*)
(*nnorm=Norm[n];*)
(*directionvector=n/nnorm;*)
(**)
(*coords1proj=CurveProjectionCoord[coords1,projplane];*)
(*coords2proj=CurveProjectionCoord[coords2, projplane];*)
(**)
(*crlist=FindCrossingscoord[coords1proj,coords2proj];*)
(**)
(*If[Length[crlist]>0,nulllist={};*)
(*Do[If[crlist[[l,5]]== endpoints[[k,3]]&&crlist[[l,6]]==endpoints[[k,4]], AppendTo[nulllist, crlist[[l]]]], {l, 1, Length[crlist]}];*)
(*crossings=DeleteElements[crlist, nulllist], crossings={}];*)
(**)
(*If[Length[crossings]>0,*)
(*(*Defining crossing vectors and determining the angle between the vectors at each crossing*)crpoints=crossingoriginalcurve[coords1, coords2, crossings, directionvector];*)
(*crossingvectors= Reap[Do[Sow[{crossings[[i,3]]-crossings[[i,1]],crossings[[i,4]]-crossings[[i,2]], VectorAngle[crossings[[i,3]]-crossings[[i,1]],crossings[[i,4]]-crossings[[i,2]]]}],{i,1,Length[crossings]}]][[2,1]];*)
(**)
(*(*Determining the position of each triple of crossings vectors and vector angle in the Linking triple based on A2 being the over curve or A1 being the over curve*)*)
(*tuplepos=Reap[Do[If[Dot[crpoints[[i,2]]-crpoints[[i,1]],directionvector]>0, Sow[crossingvectors[[i]],{x}],Sow[crossingvectors[[i]],{y}]],{i, 1, Length[crossings]} ],{x,y}];*)
(**)
(**)
(*If[Length[tuplepos[[2,1]]]> 0, cr1crossings=tuplepos[[2,1,1]], cr1crossings={}];*)
(*If[Length[tuplepos[[2,2]]]>0, cr2crossings=tuplepos[[2,2,1]], cr2crossings={}];*)
(**)
(**)
(*If[Length[cr1crossings]>0,*)
(*cr1crossinginfo= Reap[Do[If[Dot[RotationTransform[cr1crossings[[i,3]],directionvector][cr1crossings[[i,1]]], cr1crossings[[i,2]]]-Dot[RotationTransform[-cr1crossings[[i,3]],directionvector][cr1crossings[[i,1]]], cr1crossings[[i,2]]]> 0, Sow[-1], Sow[1]],{i, 1, Length[cr1crossings]}]][[2,1]],cr1crossinginfo={0}];*)
(*If[Length[cr2crossings]>0,*)
(*cr2crossinginfo= Reap[Do[If[Dot[RotationTransform[cr2crossings[[i,3]],directionvector][cr2crossings[[i,2]]], cr2crossings[[i,1]]]-Dot[RotationTransform[-cr2crossings[[i,3]],directionvector][cr2crossings[[i,2]]], cr2crossings[[i,1]]]>0, Sow[-1], Sow[1]],{i, 1, Length[cr2crossings]}]][[2,1]], cr2crossinginfo={0}];*)
(*, cr1crossinginfo=cr2crossinginfo={0}];*)
(**)
(*endcrvec1=If[end1==coords1[[1]], coords1proj[[2]]-coords1proj[[1]], coords1proj[[endpoints[[k,4]]+1]]- coords1proj[[endpoints[[k,4]]]]];*)
(*endcrvec2=If[end2==coords2[[1]], coords2proj[[2]]-coords2proj[[1]], coords2proj[[endpoints[[k,4]]+1]]- coords2proj[[endpoints[[k,4]]]]];*)
(*vecang=VectorAngle[endcrvec1,endcrvec2];*)
(**)
(*cr1= Total[cr1crossinginfo];*)
(*cr2= Total[cr2crossinginfo];*)
(**)
(*endmatched=If[Dot[RotationTransform[vecang,directionvector][endcrvec1],endcrvec2]-Dot[RotationTransform[-vecang,directionvector][endcrvec1],endcrvec2]>0,-1,1];*)
(*AppendTo[triplesseq,{cr1,cr2,endmatched}];*)
(*AppendTo[triplesall, {cr1,cr2,endmatched}], {k, 1, Length[endpoints]}];*)
(*AppendTo[triplesarray,{{i,j},Tally[triplesseq]}]]*)
(*,{j, 1, Length[listofchains]}], {i, 1, Length[listofchains]}];*)
(*triplesarray;*)
(*triplestable= {{"Curve Pairs", "Sequence with tally" }};*)
(**)
(*Do[ AppendTo[triplestable, {StringRiffle[{triplesarray[[i,1,1]],triplesarray[[i,1,2]]},{"(",",",")"}], triplesarray[[i,2]]}]*)
(*, {i, 1,Length[triplesarray]}];*)
(*output={triplestable,triplesarray, Tally[triplesall]}*)
(*]*)
(**)
(*(*Computing for all three junctions of a tensegrity triangle(Endslide)*)*)
(*junctioncomputationsEndslide[J1_,J2_,J3_]:=Module[{tupposseqJ1,tupposseqJ1table,triplesarrayJ1,triplesseqallJ1, triplesseqJ1,tupposseqJ2,tupposseqJ2table,triplesarrayJ2,triplesseqallJ2,triplesseqJ2,tupposseqJ3,tupposseqJ3table,triplesarrayJ3,triplesseqallJ3,triplesseqJ3},*)
(**)
(*triplesarrayJ1=Computelinkingtriplesendslide[J1];*)
(*triplesarrayJ2=Computelinkingtriplesendslide[J2];*)
(*triplesarrayJ3=Computelinkingtriplesendslide[J3];*)
(**)
(*{triplesarrayJ1,triplesarrayJ2,triplesarrayJ3}*)
(*]*)


(* ::Text:: *)
(*Representations:*)


(* ::Text:: *)
(*1) Linking Triples Tensor:*)


(* ::Input:: *)
(*(*Calculating distances between two sets of curves through linking triples tensor*)*)
(*distoptions[triplesarray1_, triplesarray2_,dist_]:=Module[{l,m},*)
(**)
(*l={};*)
(*m={};*)
(*Do[Do[l=Join[l,triplesarray1[[i,2,j]]], {j,1,4}],{i,1,Length[triplesarray1]}];*)
(*Do[Do[m=Join[m,triplesarray2[[i,2,j]]], {j,1,4}],{i,1,Length[triplesarray2]}];*)
(*Which[dist=="euclidean",N[EuclideanDistance[l,m]],dist=="manhattan",N[ManhattanDistance[l,m]],dist=="canberra", N[CanberraDistance[l,m]],dist=="braycurtis" ,N[BrayCurtisDistance[l,m]]]*)
(*]*)
(**)
(*(*Finding average distance from the left handed and right handed arrays*)*)
(*avgdistoptions[triplesarray_, listofarraysLH_, listofarraysRH_,dist_]:=Module[{disttableLH, disttableRH},*)
(*disttableLH={};*)
(*disttableRH={};*)
(*(*DeleteCases[listofarraysLH, triplesarray];*)
(*DeleteCases[listofarraysRH, triplesarray];*)*)
(*Do[AppendTo[disttableLH,distoptions[triplesarray,listofarraysLH[[i]],dist]], {i,1, Length[listofarraysLH]}];*)
(*Do[AppendTo[disttableRH,distoptions[triplesarray, listofarraysRH[[i]],dist]], {i,1, Length[listofarraysRH]}];*)
(*{N[Mean[disttableLH]],N[Mean[disttableRH]]}*)
(*]*)
(**)
(*(*Plotting the average distances for all given models*)*)
(*distplots[listofarraysLH_, listofarraysRH_, dist_, junction_]:=Module[{avgdistLH,avgdistRH},*)
(**)
(*avgdistLH=Table[avgdistoptions[complistLH[[i,junction]], listofarraysLH, listofarraysRH,dist], {i,1, Length[complistLH]}];*)
(*avgdistRH=Table[avgdistoptions[complistRH[[i,junction]], listofarraysLH, listofarraysRH,dist], {i,1, Length[complistRH]}];*)
(**)
(*{Show[ListPlot[Callout[#,#2]&@@@Transpose[{avgdistLH,labelsLH}],PlotStyle->{Blue}],ListPlot[Callout[#,#2]&@@@Transpose[{avgdistRH,labelsRH}],PlotStyle->{Red}],Graphics[InfiniteLine[{{0,0},{1,1}}]],PlotRange->Automatic,AxesOrigin->Automatic,AxesLabel->{"LH models","RH models"},PlotLabel->"Average distance from other models"],avgdistLH,avgdistRH}*)
(**)
(*]*)
(**)
(*(*Plotting average over all three junctions of each tensegrity triangle*)*)
(*distplotsavgoverjxns[listofarraysLH_, listofarraysRH_, dist_]:=Module[{m,n,avgdistLH,avgdistRH},*)
(**)
(**)
(*avgdistLH=Table[Mean[Table[avgdistoptions[complistLH[[i,j]] , listofarraysLH[[j]], listofarraysRH[[j]],dist],{j,1,3}]], {i,1, Length[complistLH]}];*)
(*avgdistRH=Table[Mean[Table[avgdistoptions[complistRH[[i,j]] , listofarraysLH[[j]], listofarraysRH[[j]],dist],{j,1,3}]], {i,1, Length[complistRH]}];*)
(**)
(*{Show[ListPlot[Callout[#,#2]&@@@Transpose[{avgdistLH,labelsLH}],PlotStyle->{Blue}],ListPlot[Callout[#,#2]&@@@Transpose[{avgdistRH,labelsRH}],PlotStyle->{Red}],Graphics[InfiniteLine[{{0,0},{1,1}}]],PlotRange->Automatic,AxesOrigin->Automatic,AxesLabel->{"LH models","RH models"},PlotLabel->"Average distance from other models"],avgdistLH,avgdistRH}*)
(**)
(*]*)


(* ::Text:: *)
(*2.) Column Gram matrix*)


(* ::Input:: *)
(*(*Computing the column gram matrix for a given triplesarray*)*)
(*ColumnGramMatrix[triplesarraydata_]:=Module[{tensor, flat},*)
(**)
(*tensor=TensorTranspose[{triplesarraydata[[1,2]], triplesarraydata[[2,2]], triplesarraydata[[3,2]], triplesarraydata[[4,2]], triplesarraydata[[5,2]], triplesarraydata[[6,2]]},Cycles[{{1,2,3}}]];*)
(*flat=ArrayReshape[tensor,{3,6*4}];*)
(*flat . Transpose[flat]*)
(*]*)
(**)
(*(*Calculating distances between two sets of curves through column gram matrix*)*)
(*distoptionsCGM[triplesarray1_, triplesarray2_,dist_]:=Module[{l,m},*)
(**)
(**)
(*l=Flatten[ColumnGramMatrix[triplesarray1]];*)
(*m=Flatten[ColumnGramMatrix[triplesarray2]];*)
(*Which[dist=="euclidean",N[EuclideanDistance[l,m]],dist=="manhattan",N[ManhattanDistance[l,m]],dist=="canberra", N[CanberraDistance[l,m]],dist=="braycurtis" ,N[BrayCurtisDistance[l,m]]]*)
(*]*)
(**)
(*(*Finding average distance from the left handed and right handed arrays*)*)
(*avgdistoptionsCGM[triplesarray_, listofarraysLH_, listofarraysRH_,dist_]:=Module[{disttableLH, disttableRH},*)
(*disttableLH={};*)
(*disttableRH={};*)
(*DeleteCases[listofarraysLH, triplesarray];*)
(*DeleteCases[listofarraysRH, triplesarray];*)
(*Do[AppendTo[disttableLH,distoptionsCGM[triplesarray,listofarraysLH[[i]],dist]], {i,1, Length[listofarraysLH]}];*)
(*Do[AppendTo[disttableRH,distoptionsCGM[triplesarray, listofarraysRH[[i]],dist]], {i,1, Length[listofarraysRH]}];*)
(*{N[Mean[disttableLH]],N[Mean[disttableRH]]}*)
(*]*)
(**)
(*(*Plotting the average distances for all given models*)*)
(*distplotsCGM[listofarraysLH_, listofarraysRH_, dist_, junction_]:=Module[{avgdistLH,avgdistRH},*)
(**)
(*avgdistLH=Table[avgdistoptionsCGM[complistLH[[i,junction]], listofarraysLH, listofarraysRH,dist], {i,1, Length[complistLH]}];*)
(*avgdistRH=Table[avgdistoptionsCGM[complistRH[[i,junction]], listofarraysLH, listofarraysRH,dist], {i,1, Length[complistRH]}];*)
(**)
(*{Show[ListPlot[Callout[#,#2]&@@@Transpose[{avgdistLH,labelsLH}],PlotStyle->{Blue}],ListPlot[Callout[#,#2]&@@@Transpose[{avgdistRH,labelsRH}],PlotStyle->{Red}],Graphics[InfiniteLine[{{0,0},{1,1}}]],PlotRange->Automatic,AxesOrigin->Automatic,AxesLabel->{"LH models","RH models"},PlotLabel->"Average distance from other models"],avgdistLH,avgdistRH}*)
(**)
(*]*)
(**)
(*(*Plotting average over all three junctions of each tensegrity triangle*)*)
(*distplotsCGMavgoverjxns[listofarraysLH_, listofarraysRH_, dist_]:=Module[{m,n,avgdistLH,avgdistRH},*)
(**)
(**)
(*avgdistLH=Table[Mean[Table[avgdistoptionsCGM[complistLH[[i,j]] , listofarraysLH[[j]], listofarraysRH[[j]],dist],{j,1,3}]], {i,1, Length[complistLH]}];*)
(*avgdistRH=Table[Mean[Table[avgdistoptionsCGM[complistRH[[i,j]] , listofarraysLH[[j]], listofarraysRH[[j]],dist],{j,1,3}]], {i,1, Length[complistRH]}];*)
(**)
(*{Show[ListPlot[Callout[#,#2]&@@@Transpose[{avgdistLH,labelsLH}],PlotStyle->{Blue}],ListPlot[Callout[#,#2]&@@@Transpose[{avgdistRH,labelsRH}],PlotStyle->{Red}],Graphics[InfiniteLine[{{0,0},{1,1}}]],PlotRange->Automatic,AxesOrigin->Automatic,AxesLabel->{"LH models","RH models"},PlotLabel->"Average distance from other models"],avgdistLH,avgdistRH}*)
(**)
(*]*)
(**)


(* ::Text:: *)
(*3.) Polynomial Representation:*)


(* ::Input:: *)
(*(*Calculating distances between two sets of curves through polynomial coefficient matrix*)*)
(*polyrepcoeffmatrix[triplesarray_]:=Module[{m, minter},*)
(**)
(*m={};*)
(*minter[i_]:=Module[{}, {{triplesarray[[i,2,1,3]]*triplesarray[[i,2,1,1]],0,triplesarray[[i,2,2,3]]*triplesarray[[i,2,2,1]]+triplesarray[[i,2,3,3]]*triplesarray[[i,2,3,1]],0},{0,triplesarray[[i,2,1,3]]*triplesarray[[i,2,1,2]],0,triplesarray[[i,2,2,3]]*triplesarray[[i,2,2,2]]+triplesarray[[i,2,3,3]]*triplesarray[[i,2,3,2]]},{triplesarray[[i,2,2,3]]*triplesarray[[i,2,2,1]]+triplesarray[[i,2,3,3]]*triplesarray[[i,2,3,1]],0,triplesarray[[i,2,4,3]]*triplesarray[[i,2,4,1]],0},{0,triplesarray[[i,2,2,3]]*triplesarray[[i,2,2,2]]+triplesarray[[i,2,3,3]]*triplesarray[[i,2,3,2]],0,triplesarray[[i,2,4,3]]*triplesarray[[i,2,4,2]]}}];*)
(**)
(*Do[AppendTo[m,minter[i]],{i,1,Length[triplesarray]}];*)
(*m*)
(*]*)
(**)
(*(*Calculating distances between two sets of curves through linking triples tensor*)*)
(*distoptionspolyrep[triplesarray1_, triplesarray2_,dist_]:=Module[{l,m},*)
(**)
(**)
(*l=Flatten[polyrepcoeffmatrix[triplesarray1]];*)
(*m=Flatten[polyrepcoeffmatrix[triplesarray2]];*)
(*Which[dist=="euclidean",N[EuclideanDistance[l,m]],dist=="manhattan",N[ManhattanDistance[l,m]],dist=="canberra", N[CanberraDistance[l,m]],dist=="braycurtis" ,N[BrayCurtisDistance[l,m]]]*)
(*]*)
(**)
(*(*Finding average distance from the left handed and right handed arrays*)*)
(*avgdistoptionspolyrep[triplesarray_, listofarraysLH_, listofarraysRH_,dist_]:=Module[{disttableLH, disttableRH},*)
(*disttableLH={};*)
(*disttableRH={};*)
(*DeleteCases[listofarraysLH, triplesarray];*)
(*DeleteCases[listofarraysRH, triplesarray];*)
(*Do[AppendTo[disttableLH,distoptionspolyrep[triplesarray,listofarraysLH[[i]],dist]], {i,1, Length[listofarraysLH]}];*)
(*Do[AppendTo[disttableRH,distoptionspolyrep[triplesarray, listofarraysRH[[i]],dist]], {i,1, Length[listofarraysRH]}];*)
(*{N[Mean[disttableLH]],N[Mean[disttableRH]]}*)
(*]*)
(**)
(*(*Plotting the average distances for all given models*)*)
(*distplotspolyrep[listofarraysLH_, listofarraysRH_, dist_, junction_]:=Module[{avgdistLH,avgdistRH},*)
(**)
(*avgdistLH=Table[avgdistoptionspolyrep[complistLH[[i,junction]], listofarraysLH, listofarraysRH,dist], {i,1, Length[complistLH]}];*)
(*avgdistRH=Table[avgdistoptionspolyrep[complistRH[[i,junction]], listofarraysLH, listofarraysRH,dist], {i,1, Length[complistRH]}];*)
(**)
(*{Show[ListPlot[Callout[#,#2]&@@@Transpose[{avgdistLH,labelsLH}], PlotStyle->{Blue}],ListPlot[Callout[#,#2]&@@@Transpose[{avgdistRH,labelsRH}], PlotStyle->{Red}],Graphics[InfiniteLine[{{0,0},{1,1}}]],PlotRange-> Automatic, AxesOrigin->{0,0},AxesLabel->{"LH models", "RH models"}, PlotLabel->"Average distance from other models"], avgdistLH, avgdistRH}*)
(**)
(*]*)
(**)
(*(*Plotting average over all three junctions of each tensegrity triangle*)*)
(*distplotspolyrepavgoverjxns[listofarraysLH_, listofarraysRH_, dist_]:=Module[{m,n,avgdistLH,avgdistRH, plxmin, plxmax, plymin, plymax},*)
(**)
(**)
(*avgdistLH=Table[Mean[Table[avgdistoptionspolyrep[complistLH[[i,j]] , listofarraysLH[[j]], listofarraysRH[[j]],dist],{j,1,3}]], {i,1, Length[complistLH]}];*)
(*avgdistRH=Table[Mean[Table[avgdistoptionspolyrep[complistRH[[i,j]] , listofarraysLH[[j]], listofarraysRH[[j]],dist],{j,1,3}]], {i,1, Length[complistRH]}];*)
(**)
(*{Show[ListPlot[Callout[#,#2]&@@@Transpose[{avgdistLH,labelsLH}], PlotStyle->{Blue}],ListPlot[Callout[#,#2]&@@@Transpose[{avgdistRH,labelsRH}], PlotStyle->{Red}],Graphics[InfiniteLine[{{0,0},{1,1}}]],PlotRange-> Automatic, AxesOrigin->Automatic,AxesLabel->{"LH models", "RH models"}, PlotLabel->"Average distance from other models"], avgdistLH, avgdistRH}*)
(**)
(*]*)
(**)
(**)
